
import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { ChefHat, ArrowRight, Plus, Database, ShieldCheck, RefreshCw, CheckCircle2, Cloud, CloudOff, LogIn, LogOut, User as UserIcon, Mail, Lock, Key, Link as LinkIcon, Leaf, ShieldAlert, Info, ExternalLink, AlertTriangle, Ghost, RotateCcw, Copy, Check, Search, ShieldQuestion, UploadCloud, DownloadCloud, Unlock } from 'lucide-react';
import { createClient, User } from '@supabase/supabase-js';
import RecipesTab from './components/RecipesTab';
import Navigation from './components/Navigation';
import RecipeForm from './components/RecipeForm';
import MealPlanTab from './components/MealPlanTab';

// Types & Interfaces
export type DayOfWeek = 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday';
export type TimeSlot = 'Pre-Breakfast' | 'Breakfast' | 'Lunch' | 'Snacks' | 'Dinner' | 'Post-Dinner';
export interface Ingredient { item: string; quantity: number; unit: string; }
export interface PrepTask { task: string; duration: string; }
export interface Recipe {
  id: string;
  name: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  ingredients: Ingredient[];
  prepTasks: PrepTask[];
  macros: { calories: number; protein: number; carbs: number; fat: number; };
  synced?: boolean;
}
export type UserProfile = 'V' | 'M';
export interface PlannedMeal { recipeId: string; profile: UserProfile; }
export interface MealPlan { [key: string]: { [key: string]: PlannedMeal[]; }; }

const DB_NAME = 'MealPrepVM_Vault';
const STORE_NAME = 'AppData';
const PUBLIC_USER_ID = '00000000-0000-0000-0000-000000000000';

const SQL_SETUP = `-- FIX: REMOVE AUTH REQUIREMENT (Run this if saves fail)
ALTER TABLE recipes DROP CONSTRAINT IF EXISTS recipes_user_id_fkey;
ALTER TABLE meal_plans DROP CONSTRAINT IF EXISTS meal_plans_user_id_fkey;

-- INITIAL SETUP (If starting fresh)
create table if not exists recipes (
  id text primary key,
  user_id uuid default '00000000-0000-0000-0000-000000000000',
  name text not null,
  difficulty text,
  ingredients jsonb,
  prep_tasks jsonb,
  macros jsonb,
  created_at timestamp with time zone default now()
);

create table if not exists meal_plans (
  id bigint generated by default as identity primary key,
  user_id uuid default '00000000-0000-0000-0000-000000000000',
  day text not null,
  slot text not null,
  meals jsonb,
  unique(user_id, day, slot)
);

alter table recipes disable row level security;
alter table meal_plans disable row level security;`;

// --- INDEXEDDB HELPER ---
const dbPromise = (async () => {
  return new Promise<IDBDatabase>((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, 9);
    request.onupgradeneeded = (e: any) => {
      const db = request.result;
      if (!db.objectStoreNames.contains(STORE_NAME)) {
        db.createObjectStore(STORE_NAME);
      }
    };
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
})();

const saveDataLocal = async (key: string, val: any) => {
  const db = await dbPromise;
  const tx = db.transaction(STORE_NAME, 'readwrite');
  tx.objectStore(STORE_NAME).put(val, key);
  return new Promise((res) => (tx.oncomplete = res));
};

const getDataLocal = async (key: string) => {
  const db = await dbPromise;
  return new Promise((resolve) => {
    const request = db.transaction(STORE_NAME).objectStore(STORE_NAME).get(key);
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => resolve(null);
  });
};

const App: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'home' | 'recipes' | 'mealplan' | 'settings'>('home');
  const [recipes, setRecipes] = useState<Recipe[]>([]);
  const [mealPlan, setMealPlan] = useState<MealPlan>({});
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [editingRecipe, setEditingRecipe] = useState<Recipe | null>(null);
  const [syncStatus, setSyncStatus] = useState<'synced' | 'syncing' | 'error' | 'local-only' | 'locked'>('locked');
  const [isLoading, setIsLoading] = useState(true);
  const [criticalError, setCriticalError] = useState<{title: string, msg: string, showSql?: boolean} | null>(null);
  const [isPushing, setIsPushing] = useState(false);
  const [copied, setCopied] = useState(false);
  
  const [sbConfig, setSbConfig] = useState<{ url: string; key: string } | null>(null);
  const [user, setUser] = useState<User | null>(null);

  const supabase = useMemo(() => {
    if (!sbConfig?.url || !sbConfig?.key) return null;
    try {
      return createClient(sbConfig.url, sbConfig.key);
    } catch (e) {
      return null;
    }
  }, [sbConfig]);

  const fetchAndMergeCloudData = useCallback(async () => {
    if (!supabase) return;
    setSyncStatus('syncing');
    try {
      const [{ data: cloudRecipes, error: recError }, { data: cloudPlans }] = await Promise.all([
        supabase.from('recipes').select('*'),
        supabase.from('meal_plans').select('*')
      ]);

      if (recError) {
        if (recError.code === '42P01') throw { title: "Setup Required", msg: "Table 'recipes' missing.", showSql: true };
        throw recError;
      }

      setRecipes(prevLocal => {
        const recipeMap = new Map<string, Recipe>();
        prevLocal.forEach(r => recipeMap.set(r.id, { ...r, synced: false }));
        cloudRecipes?.forEach((r: any) => {
          recipeMap.set(r.id, {
            id: r.id,
            name: r.name,
            difficulty: r.difficulty,
            ingredients: r.ingredients,
            prepTasks: r.prep_tasks || [],
            macros: r.macros,
            synced: true
          });
        });
        const final = Array.from(recipeMap.values());
        saveDataLocal('recipes', final);
        return final;
      });

      if (cloudPlans) {
        setMealPlan(prev => {
          const newPlan = { ...prev };
          cloudPlans.forEach((p: any) => {
            if (!newPlan[p.day]) newPlan[p.day] = {};
            newPlan[p.day][p.slot] = p.meals;
          });
          saveDataLocal('mealplan', newPlan);
          return newPlan;
        });
      }

      setSyncStatus('synced');
    } catch (err: any) {
      setSyncStatus('error');
      if (err.showSql || err.code === '23503') setCriticalError({ 
        title: "Constraint Error", 
        msg: "Your database is blocking 'Public Mode'. Run the SQL below to fix.", 
        showSql: true 
      });
      console.error("Sync Error:", err);
    }
  }, [supabase]);

  const pushLocalToCloud = async () => {
    if (!supabase || recipes.length === 0) return;
    setIsPushing(true);
    setSyncStatus('syncing');
    try {
      const payload = recipes.map(r => ({
        id: r.id,
        user_id: user?.id || PUBLIC_USER_ID,
        name: r.name,
        difficulty: r.difficulty,
        ingredients: r.ingredients,
        prep_tasks: r.prepTasks,
        macros: r.macros
      }));

      const { error } = await supabase.from('recipes').upsert(payload);
      if (error) throw error;

      setRecipes(current => current.map(r => ({ ...r, synced: true })));
      setSyncStatus('synced');
    } catch (err: any) {
      if (err.code === '23503') {
        setCriticalError({ title: "Save Blocked", msg: "Database constraint violated. Run the SQL fix.", showSql: true });
      } else {
        alert(`Push failed: ${err.message}`);
      }
      setSyncStatus('error');
    } finally {
      setIsPushing(false);
    }
  };

  const handleLockVault = useCallback(async () => {
    if (!confirm("Disconnect Cloud?")) return;
    await saveDataLocal('supabase_config', null);
    setSbConfig(null);
    setSyncStatus('locked');
    setUser(null);
  }, []);

  useEffect(() => {
    const init = async () => {
      const savedConfig = await getDataLocal('supabase_config') as { url: string; key: string };
      if (savedConfig?.url && savedConfig?.key) {
        setSbConfig(savedConfig);
        setSyncStatus('local-only');
      }
      const storedRecipes = await getDataLocal('recipes') as Recipe[];
      const storedPlan = await getDataLocal('mealplan') as MealPlan;
      if (storedRecipes) setRecipes(storedRecipes);
      if (storedPlan) setMealPlan(storedPlan);
      setIsLoading(false);
    };
    init();
  }, []);

  useEffect(() => {
    if (!supabase) return;
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      setUser(session?.user ?? null);
      fetchAndMergeCloudData();
    });
    return () => subscription.unsubscribe();
  }, [supabase, fetchAndMergeCloudData]);

  const handleSaveRecipe = async (recipe: Recipe) => {
    setRecipes(prev => {
      const next = prev.some(r => r.id === recipe.id)
        ? prev.map(r => r.id === recipe.id ? recipe : r)
        : [...prev, recipe];
      saveDataLocal('recipes', next);
      return next;
    });
    setIsFormOpen(false);

    if (supabase) {
      setSyncStatus('syncing');
      try {
        const { error } = await supabase.from('recipes').upsert({
          id: recipe.id,
          name: recipe.name,
          difficulty: recipe.difficulty,
          ingredients: recipe.ingredients,
          prep_tasks: recipe.prepTasks,
          macros: recipe.macros,
          user_id: user?.id || PUBLIC_USER_ID
        });
        if (error) throw error;

        setRecipes(current => current.map(r => r.id === recipe.id ? { ...r, synced: true } : r));
        setSyncStatus('synced');
      } catch (err: any) {
        setSyncStatus('error');
        if (err.code === '23503') {
           setCriticalError({ title: "Save Error", msg: "Constraint failure. Run the SQL fix provided.", showSql: true });
        }
        console.error("Cloud Save Error:", err);
      }
    }
  };

  const handleDeleteRecipe = async (id: string) => {
    if (!confirm("Delete this recipe?")) return;
    setRecipes(prev => {
      const next = prev.filter(r => r.id !== id);
      saveDataLocal('recipes', next);
      return next;
    });
    if (supabase) {
      try {
        await supabase.from('recipes').delete().eq('id', id);
        setSyncStatus('synced');
      } catch (e) {
        setSyncStatus('error');
      }
    }
  };

  const handleUpdatePlan = async (day: string, slot: string, meals: PlannedMeal[]) => {
    setMealPlan(prev => {
      const next = { ...prev, [day]: { ...(prev[day] || {}), [slot]: meals } };
      saveDataLocal('mealplan', next);
      return next;
    });

    if (supabase) {
      setSyncStatus('syncing');
      try {
        const { error } = await supabase.from('meal_plans').upsert({
          user_id: user?.id || PUBLIC_USER_ID,
          day,
          slot,
          meals
        }, { onConflict: 'user_id,day,slot' });
        if (error) throw error;
        setSyncStatus('synced');
      } catch (err) {
        setSyncStatus('error');
      }
    }
  };

  if (isLoading) return <div className="flex items-center justify-center min-h-screen bg-green-50"><RefreshCw className="w-8 h-8 text-green-600 animate-spin" /></div>;

  if (criticalError) {
    return (
      <div className="min-h-screen bg-green-950 flex flex-col items-center justify-center p-6 ios-safe-top ios-safe-bottom">
        <div className="w-full max-w-xl bg-white p-8 sm:p-12 rounded-[3.5rem] shadow-2xl space-y-8 overflow-y-auto max-h-[90vh]">
          <div className="text-center space-y-4">
            <div className="bg-red-50 w-20 h-20 rounded-[2rem] flex items-center justify-center mx-auto"><AlertTriangle className="w-10 h-10 text-red-600" /></div>
            <h1 className="text-3xl font-black text-gray-900">{criticalError.title}</h1>
            <p className="text-sm text-gray-500">{criticalError.msg}</p>
          </div>
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-[10px] font-black text-gray-400 uppercase tracking-widest">SQL FIX (Run in Supabase)</span>
              <button onClick={() => { navigator.clipboard.writeText(SQL_SETUP); setCopied(true); setTimeout(()=>setCopied(false), 2000); }} className="text-[10px] font-black text-green-600 uppercase flex items-center gap-1">
                {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />} {copied ? 'Copied' : 'Copy SQL'}
              </button>
            </div>
            <div className="bg-gray-900 rounded-2xl p-5 overflow-x-auto"><pre className="text-[11px] text-green-400 font-mono leading-relaxed">{SQL_SETUP}</pre></div>
          </div>
          <button onClick={() => { setCriticalError(null); fetchAndMergeCloudData(); }} className="w-full bg-green-900 text-white py-5 rounded-[2rem] font-bold">I ran the SQL, Try Again</button>
          <button onClick={handleLockVault} className="w-full text-red-600 font-bold text-xs uppercase tracking-widest">Disconnect</button>
        </div>
      </div>
    );
  }

  if (!sbConfig) {
    return (
      <div className="min-h-screen bg-green-950 flex items-center justify-center p-6 ios-safe-top ios-safe-bottom">
        <div className="w-full max-w-lg">
          <form onSubmit={async (e) => {
            e.preventDefault();
            const formData = new FormData(e.currentTarget);
            let url = (formData.get('url') as string).trim();
            const key = (formData.get('key') as string).trim();
            if (!url.startsWith('https://')) url = `https://${url.includes('.supabase.co') ? url : url + '.supabase.co'}`;
            const config = { url, key };
            await saveDataLocal('supabase_config', config);
            setSbConfig(config);
            setSyncStatus('local-only');
          }} className="bg-white/5 backdrop-blur-3xl border border-white/10 p-8 sm:p-12 rounded-[3.5rem] shadow-2xl space-y-8 animate-in zoom-in duration-700">
            <div className="text-center space-y-3">
              <div className="bg-gradient-to-br from-green-400 to-emerald-600 inline-flex p-5 rounded-[2rem] shadow-2xl mb-4"><ShieldCheck className="w-12 h-12 text-white" /></div>
              <h1 className="text-4xl font-black text-white tracking-tighter">Nature Vault</h1>
              <p className="text-green-300/60 text-xs font-bold uppercase tracking-widest">Supabase Gateway</p>
            </div>
            <div className="space-y-5">
              <input name="url" required placeholder="Project URL" className="w-full bg-white/5 border border-white/10 rounded-[1.5rem] py-5 px-6 text-white placeholder-green-800 outline-none" />
              <input name="key" type="password" required placeholder="Anon Key" className="w-full bg-white/5 border border-white/10 rounded-[1.5rem] py-5 px-6 text-white placeholder-green-800 outline-none" />
            </div>
            <button type="submit" className="w-full bg-gradient-to-r from-green-400 to-emerald-500 text-green-950 py-5 rounded-[2rem] font-black text-[10px] uppercase tracking-widest shadow-xl">Connect Cloud</button>
          </form>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col min-h-screen max-w-2xl mx-auto bg-white shadow-2xl relative overflow-hidden pb-24 ios-safe-top">
      <div className="fixed top-4 right-4 z-[60] flex items-center gap-2">
        <div className={`bg-white/80 backdrop-blur shadow-sm border border-gray-100 px-3 py-1.5 rounded-full flex items-center gap-2`}>
          {syncStatus === 'syncing' ? <RefreshCw className="w-3 h-3 text-amber-500 animate-spin" /> : 
           syncStatus === 'synced' ? <Cloud className="w-3 h-3 text-green-600" /> : <CloudOff className="w-3 h-3 text-gray-400" />}
          <span className="text-[10px] font-black text-gray-500 uppercase tracking-widest">{syncStatus}</span>
        </div>
      </div>

      <main className="flex-1 flex flex-col p-6 page-transition">
        {activeTab === 'home' && (
          <div className="flex-1 flex flex-col items-center justify-center space-y-8 animate-in fade-in duration-700">
            <div className="bg-green-600 p-6 rounded-[2.5rem] shadow-2xl"><ChefHat className="w-16 h-16 text-white" /></div>
            <div className="text-center">
              <h1 className="text-4xl font-black text-green-900 tracking-tight">Meal Prep-VM</h1>
              <p className="text-green-700 font-bold tracking-widest uppercase text-xs mt-2 flex items-center justify-center gap-2"><Database className="w-3 h-3" /> Cloud Linked</p>
            </div>
            <button onClick={() => setActiveTab('recipes')} className="group flex items-center justify-center gap-3 bg-green-900 text-white px-8 py-5 rounded-[2rem] font-bold shadow-xl active:scale-95 transition-all">Go to Recipes <ArrowRight className="w-5 h-5" /></button>
          </div>
        )}

        {activeTab === 'recipes' && (
          <div className="animate-in slide-in-from-right duration-500">
            <header className="mb-8 flex justify-between items-end">
              <div><h2 className="text-2xl font-bold text-gray-900">Catalog</h2></div>
              <button onClick={() => { setEditingRecipe(null); setIsFormOpen(true); }} className="p-3 bg-green-600 text-white rounded-2xl shadow-lg active:scale-95"><Plus className="w-6 h-6" /></button>
            </header>
            <RecipesTab recipes={recipes} onEdit={(r) => { setEditingRecipe(r); setIsFormOpen(true); }} onDelete={handleDeleteRecipe} />
          </div>
        )}

        {activeTab === 'mealplan' && (
          <MealPlanTab recipes={recipes} mealPlan={mealPlan} onUpdatePlan={handleUpdatePlan} />
        )}

        {activeTab === 'settings' && (
          <div className="animate-in fade-in duration-500 space-y-8 pb-10">
            <header><h2 className="text-2xl font-bold text-gray-900">Setup</h2></header>
            
            <section className="bg-white p-8 rounded-[2.5rem] border border-gray-100 shadow-sm space-y-6">
              <div className="flex items-center gap-3"><div className="p-2 bg-indigo-50 rounded-xl text-indigo-600"><UserIcon className="w-5 h-5" /></div><h3 className="font-bold text-gray-900">Cloud Sync</h3></div>
              
              <div className="bg-amber-50 p-5 rounded-2xl border border-amber-100 space-y-3">
                <div className="flex items-center justify-between">
                  <p className="text-xs font-bold text-amber-900">Push Utility</p>
                  <span className="text-[9px] font-black text-amber-600 uppercase tracking-widest">{recipes.filter(r => !r.synced).length} unsynced items</span>
                </div>
                <button 
                  onClick={pushLocalToCloud} 
                  disabled={isPushing}
                  className="w-full bg-amber-600 text-white py-3 rounded-xl font-bold text-xs flex items-center justify-center gap-2 hover:bg-amber-700 transition-all disabled:opacity-50"
                >
                  {isPushing ? <RefreshCw className="w-3 h-3 animate-spin" /> : <UploadCloud className="w-3 h-3" />}
                  Push All to Supabase
                </button>
              </div>

              <div className="p-4 bg-green-50 rounded-2xl border border-green-100">
                <p className="text-[10px] font-black text-green-700 uppercase tracking-widest mb-1">Status</p>
                <p className="text-[11px] text-green-600 leading-relaxed">Connected to Supabase. Every change is synced automatically if the cloud is reachable.</p>
              </div>
            </section>
            
            <section className="bg-gray-50 p-6 rounded-[2rem] border border-gray-100 flex items-center justify-between">
              <div className="flex items-center gap-3 overflow-hidden">
                <Cloud className="w-5 h-5 text-gray-400 flex-shrink-0" />
                <div className="overflow-hidden"><p className="text-sm font-bold text-gray-900">Project Endpoint</p><p className="text-[10px] text-gray-500 truncate">{sbConfig?.url}</p></div>
              </div>
              <button onClick={handleLockVault} className="p-3 bg-white text-gray-400 rounded-xl hover:text-red-500 transition-colors shadow-sm"><Lock className="w-4 h-4" /></button>
            </section>
          </div>
        )}
      </main>
      <Navigation activeTab={activeTab} setActiveTab={setActiveTab} />
      {isFormOpen && (
        <RecipeForm 
          onClose={() => setIsFormOpen(false)} 
          onSave={handleSaveRecipe} 
          initialData={editingRecipe} 
        />
      )}
    </div>
  );
};

export default App;
